import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import Navigation from "@/components/Navigation";
import CardNav from "@/components/CardNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Shay Kintanar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const items = [
    {
      label: "About",
      bgColor: "#0D0716",
      textColor: "#fff",
      links: [{ label: "Get to Know Me!", href: "/experiences" }],
    },
    {
      label: "Projects",
      bgColor: "#7863bf",
      textColor: "#fff",
      links: [{ label: "View My Projects!", href: "/projects" }],
    },
    {
      label: "Contact",
      bgColor: "#977df0",
      textColor: "#fff",
      links: [
        {
          label: "Email",
          ariaLabel: "Email us",
          href: "/contact",
        },
        {
          label: "Facebook",
          ariaLabel: "Facebook",
          href: "https://www.facebook.com/shay.kintanar/",
          target: "_blank",
        },
        {
          label: "LinkedIn",
          ariaLabel: "LinkedIn",
          href: "https://www.linkedin.com/in/shay-kintanar-07b53b30b/",
          target: "_blank",
        },
      ],
    },
  ];

  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />

      <body className="bg-background min-h-screen">
        <div className="flex h-30">
          <CardNav
            logoAlt="Company Logo"
            items={items}
            baseColor="#fff"
            menuColor="#000"
            buttonBgColor="#111"
            buttonTextColor="#fff"
            ease="power3.out"
          />
        </div>

        {children}
      </body>
    </html>
  );
}
